services:
  app:
    container_name: payment-splitter-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - "3006:3006"
    depends_on:
      - rabbitmq
      - mongodb
    environment:
      - PORT=3006
      - MOCK_DATABASE=false
      - MOCK_MESSAGE_QUEUE=false
      - RABBITMQ_URL=amqp://rabbitmq
      - MONGODB_URL=mongodb://mongodb:27017/payment-splitter
    command: npm run dev
    networks:
      - app-network

  rabbitmq:
    container_name: payment-splitter-rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - app-network

  mongodb:
    container_name: payment-splitter-mongodb
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - app-network

  mongo_express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment: 
      - ME_CONFIG_MONGODB_URL=mongodb://mongodb:27017
    depends_on:
      - mongodb
    restart: always
    networks:
      - app-network

networks:
  app-network:

volumes:
  rabbitmq_data:
  mongodb_data:
